// -*- C++ -*-
//
// generated by wxGlade 1.0.0a5 on Mon Sep  7 15:31:29 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef MAINWINODW_H
#define MAINWINODW_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class mainwinodw: public wxFrame {
public:
    // begin wxGlade: mainwinodw::ids
    // end wxGlade

    mainwinodw(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: mainwinodw::attributes
    // end wxGlade
}; // wxGlade: end class


#endif // MAINWINODW_H
