// -*- C++ -*-
//
// generated by wxGlade 1.0.0a5 on Mon Sep  7 15:31:29 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "mainwinodw.h"

// begin wxGlade: ::extracode
// end wxGlade


mainwinodw::mainwinodw(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: mainwinodw::mainwinodw
    SetSize(wxSize(300, 150));
    SetTitle(wxT("frame"));
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, wxT("test"));
    sizer_1->Add(label_1, 0, 0, 0);
    
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

